#!/usr/bin/env python
# A simple script to generate different hash types
# Useful for CTFs, practicing password cracking, or
# whatever you wanna do with it.
# Stephen Garrison 2024

import hashlib
import sys
from pyfiglet import Figlet

ALGOS = ['md5', 'sha1', 'sha224', 'sha256', 'sha384', 'sha512']

def main():
    print(banner('Gen Hash'))

    if len(sys.argv) < 3 or sys.argv[1] == '-h' or sys.argv[2] not in ALGOS:
        usage()

    else:
        inText = sys.argv[1]
        hashType = sys.argv[2]
        hashedPass = hash_text(inText, hashType)
        print('PLAINTEXT[*]> {}'.format(inText))
        print('HASH TEXT[*]> {}'.format(hashedPass))
        sys.exit()
    
def usage():
    print('Usage: genhash [PLAINTEXT] [HASHTYPE]')
    print('HAHTYPES: {}'.format(ALGOS))
    sys.exit()

def hash_text(plainText, hashAlgo):
    hex_hash = hashlib.new(hashAlgo, plainText.encode('utf8')).hexdigest()
    return hex_hash

def banner(bannerText):
    setFont = Figlet(font='future') # pagga/future/mono9 or 12 are good fonts
    bannerString = setFont.renderText(bannerText)
    return bannerString

if __name__ == '__main__':
    main()


